[package]
name = "tetanus-attack"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.14"
rand = "0.8"
getrandom = { version = "0.3", features = ["wasm_js"] }
uuid = { version = "1.x", features = ["js"] }
